name: ib_trade_dart
description: Interactive Brokers SDK for Dart and Flutter.
version: 0.1.0
homepage: https://github.com/Aloshanai/ib_trade_dart
repository: https://github.com/Aloshanai/ib_trade_dart
issue_tracker: https://github.com/Aloshanai/ib_trade_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

